<a href="https://colab.research.google.com/github/rakshamishra54/Amazon_Sales_Analytics/blob/main/Amazon_Sales_analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
import pandas as pd , sqlite3
from pathlib import Path

my_drive = Path('/content/drive/MyDrive')
conn = sqlite3.connect('/content/amazon_sales.db')
files = {
    'orders_amazon.csv': 'orders',
    'shipping.csv': 'shipping',
    'payments.csv': 'payments',
    'order_items.csv': 'order_items',
    'customers_amazon.csv': 'customers',
    'inventory.csv': 'inventory',
    'sellers.csv': 'sellers',
    'products.csv': 'products',
    'category.csv': 'category'
}

for filename, table_name in files.items():
    matches = list(my_drive.rglob(filename))
    df = pd.read_csv(matches[0])
    df.columns = df.columns.str.strip()
    df.to_sql(table_name, conn, if_exists='replace', index=False)
    print(f" {table_name}: {len(df)} rows loaded")

 orders: 21629 rows loaded
 shipping: 21141 rows loaded
 payments: 21629 rows loaded
 order_items: 21629 rows loaded
 customers: 898 rows loaded
 inventory: 765 rows loaded
 sellers: 54 rows loaded
 products: 765 rows loaded
 category: 6 rows loaded

In [22]:
def run(query):
    return pd.read_sql_query(query, conn)

run("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
""")

          name
0       orders
1     shipping
2     payments
3  order_items
4    customers
5    inventory
6      sellers
7     products
8     category

In [23]:
##Show me all columns from the customers table
run("""
SELECT *
FROM customers
LIMIT 5;
""")

   Customer ID first_name last_name      state
0          894     Ursula       Lee  Wisconsin
1          895     Samuel     Clark  Wisconsin
2          896    Patrick     Scott  Wisconsin
3          897        Mia     Davis  Wisconsin
4          898       Jake     Davis  Wisconsin